name: Build

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 13
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute Gradle build
        run: ./gradlew build -PtargetPlatform=musl
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lavalink.jar
          path: |
            LavalinkServer/build/libs/Lavalink.jar
            LavalinkServer/build/libs/Lavalink-musl.jar
